Testing
francksefu/math-magicien pull request #7
Opened 2023-04-13 20:11 UTC by francksefu

Set up React Testing Library. -> done
Write unit tests for the files operate.js and calculate.js using Jest. -> done
Create unit tests for all React components: -> done
Use Jest snapshots to test the components. -> done
Use React Testing Library to simulate user interaction. -> done
Run your full tests suite using Jest. All tests should pass. -> done

2023-04-13 20:55 UTC, Shisui6 requested changes
Hi @francksefu, @ghreza-crypto, and @Ali-0111

# Requires Changes 🍀
You have done a great job so far!👏👏
Your project is almost there. We just need to work on a few issues🪲.

## Highlights
- Tests are passing ✅
- Added tests for logic files ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

_Check the comments under the review._

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 20:55 UTC, Shisui6 commented on src/App.test.js
> +  expect(render(<Quotes />)).toMatchSnapshot();
Nice job using jest snapshots to test your components✨. However, according to the project requirements, you are also supposed to write unit tests for **all** your components using the react testing library. The react testing library provides many useful functions for interacting with your components during testing. Take a look at this [tutorial](https://testing-library.com/docs/react-testing-library/example-intro) to see examples of the library in action. You can also have a look at this [cheatsheet](https://testing-library.com/docs/react-testing-library/cheatsheet) to see common queries used in the library. 

Please create separate test files for each of your components using functions from the react testing library🙏

2023-04-13 20:55 UTC, Shisui6 commented on src/App.test.js
>  test('renders learn react link', () => {
[Optional] It's considered best practice to organize all your test files in a single `__tests__` folder in your `src` directory. This way, your test files are easy to locate and categorize. I strongly suggest you implement this practise👍

2023-04-14 07:02 UTC, andersonlebon approved these changes
## Hi @francksefu 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 14:12 UTC, merged